[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
voting_system = "5NRWQgocGR6uN4YyM83gpu3HbeFnx9ojHYwzDMJKzSqj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lorenzodelia/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
